### PR TITLE
Log: allow cron to insert logs in oc_t_log table

### PR DESCRIPTION
**Pull request by adrienrn**
In `oc_t_log`, the `s_ip` column is `NOT NULL`

When PHP is running from the command-line, `$_SERVER` is null, then it's impossible to insert logs from cron jobs.

``` php
if (!isset($_SERVER) || (isset($_SERVER) && !isset($_SERVER['REMOTE_ADDR']))) {
    // CRON.
    $_SERVER['REMOTE_ADDR']= '127.0.0.1';
}
```

It may be wise to switch the `s_ip` to `NULL` and make the update in the next release, don't know what's the method you prefer.

### CODE REVIEW

**Comment by dev-101** [comment]
I am curious about this PR.

Is it possible that we add CLI condition into if clause to make *sure* it is comming from CLI? Just in case.

**Comment by dev-101** [comment]
http://stackoverflow.com/questions/933367/php-how-to-best-determine-if-the-current-invocation-is-from-cli-or-web-server

**Comment by conejoninja** [comment]
In the case it's not CLI and it doesn't have a REMOTE_ADDR the log will fail (due to not null), so we need to set a default value anyway

**Comment by dev-101** [comment]
No, I was focused on security aspect, say if a request comes without REMOTE_ADDS set (while $_SERVER is). Not sure if that can happen in practice, though. I don't have a problem with CLI and default value.

http://stackoverflow.com/questions/4278982/is-it-possible-that-remote-addr-could-be-blank

**Comment by dev-101** [comment]
Simplifying it, we could remove or condition part and it will be fine ($_SERVER is null in that case).
That will mean it is from local.

**Comment by dev-101** [comment]
>			// CLI CRON
>			if ( !isset($_SERVER) && !isset($_SERVER['REMOTE_ADDR']) ) {
>				$_SERVER['REMOTE_ADDR']= '127.0.0.1';
>			}

**Pull request merged**
