### PR TITLE
Add depatments and update french régions and cities

### PR DESCRIPTION
**Pull request by zorodimanche**
Hello, you can update the French version because france is divided into regions, departments and cities. But in the script it lacks departments and more regions do not match. 
Thank you

### CODE REVIEW

**Comment by dev-101** [comment]
Osclass does not support 'departments'. Only countries, regions, cities (and city area partially).
You can modify your theme to use something of those available fields.

Also, do not create wrong or empty **pull requests** like this, instead open an **issue**:
https://github.com/osclass/Osclass/issues/new

**Comment by zorodimanche** [comment]
But is there a theme with French regions / department / cities

**Comment by dev-101** [comment]
I really do not know, there are some themes, check market and forums.

**Comment by zorodimanche** [comment]
tanks

**Pull request closed without merging**
