### PR TITLE
Fix alert for loggedin & non-loggedin users

### PR DESCRIPTION
**Pull request by dev-subhojit**
Signed-off-by: Subhojit Mukherjee <subhojit@defineway.com>

### CODE REVIEW

**Comment by dev-101** [comment]
Hi dev-subhojit, thanks. I have confirmed this bug, too. But this PR will not be accepted, unless you make it to hotfixes (or develop) branch, not master.

**Comment by dev-subhojit** [comment]
Hi @dev-101 can you guide me how to do that?

**Comment by dev-101** [comment]
Select the hotfixes branch before making PR.

**Comment by dev-subhojit** [comment]
Hello @dev-101 , already I created the branch named "alert-fix"

**Pull request closed without merging**
