### PR TITLE
cyrillic substitution

### PR DESCRIPTION
**Pull request by conejoninja**
This need testing

### CODE REVIEW

**Comment by dev-101** [comment]
Osclass will be sad because of - and _ :)

**Comment by conejoninja** [comment]
@dev-101 Thanks, I just copied the code from the forum to not forget about it, I need to test this, probably found a multi-language solution instead of this

**Comment by dev-101** [comment]
Also, the Cyrillic transliteration above is optimized for Russian/Ukrainian variants only. Not all variants use the same transliteration principle (e.g. instead of 2 only 1 latin letter, different perhaps and so on). Not an easy matter to satisfy all languages I'm afraid. If we could add some filter/hook so that it can be possible to modify this outside core will be great.

**Comment by dev-101** [comment]
Also, I cannot find it now, WordPress has a massive ~ similar file like this... will check.

**Pull request closed without merging**
