### PR TITLE
recaptcha preference section upgrade fix

### PR DESCRIPTION
**Pull request by dev-101**

### CODE REVIEW

**Comment by dev-101** [comment]
Forgot to add new func, we also need to fix this on existing upgraded installations.

**Comment by conejoninja** [comment]
not sure what the issue here, could you explain? you are deleting the preference

**Comment by dev-101** [comment]
Conejo, it passed 'STRING' for 'section' - it will not work!

Problem is now how to treat this and not break installations where users manually fixed it in database.

**Comment by conejoninja** [comment]
thanks I didn't see it

**Comment by dev-101** [comment]
:+1:

**Pull request merged**
