### PR TITLE
before_user_delete hook

### PR DESCRIPTION
**Pull request by dev-101**
before_user_delete hook

### CODE REVIEW

**Comment by conejoninja** [comment]
not sure why the order change, it has no effect. That hook should be a filter instead maybe

**Comment by dev-101** [comment]
Hi Conejo,
I need it to avoid core change every time ;)
Filter is of no use to me at that point, but you can also add a filter in next line, if you like.

**Comment by conejoninja** [comment]
No problem accepting it, but I can't see how the change could affect to anything

**Comment by dev-101** [comment]
Oh, don't remember why I did it, to save on performance I guess. :)

**Pull request merged**
