### PR TITLE
rename ImageResizer => ImageProcessing

### PR DESCRIPTION
**Pull request by dev-101**
Old name is completely misleading since the merger of old classes into one, unified class does so much more than image resizing funcs.

### CODE REVIEW

**Comment by conejoninja** [comment]
This changes the name of the file only, not the class, not the code where it's used and doing this change probably will break some plugins too. We could use class_alias, but that requires PHP >= 5.3.0 "might" break some installations, people are still using the outdated 5.2.x ... not sure what to do about this issue

**Comment by dev-101** [comment]
Hi Conejo,
I have not changed the class name on purpose (for compatibility reasons). Changing the file so far have not broken anything on my end (the only way that something may go wrong is with manual updates, where someone forgets to apply all the changes).

Anyway, this is more of a nitpicking, so I am closing this.
Thanks

**Comment by conejoninja** [comment]
One fix may be to ship both files ImageResizer (not loaded) + ImageProcessing (loaded) and check PHP version, if PHP >=5.3 use class_alias , else, load ImageResizer

I agree that's not the better name, and we should change it sometime in the future. Will reopen the PR to not forget about it

**Comment by dev-101** [comment]
Aww, let's not duplicate files :)

On a plus side, by the time decision will be made about the change, PHP 5.3.0 will be long history, so less worries for compatibility issues. No hurry.

**Pull request closed without merging**
