### PR TITLE
Fix url bug with child-themes

### PR DESCRIPTION
**Pull request by groomain**
Child themes can't work properly if the files missing in the child theme aren't loaded with the parent. 

Fix osc_current_web_theme_url()

### CODE REVIEW

**Comment by dev-101** [comment]
L#224 seems redundant

**Comment by groomain** [comment]
L#224 ? :)

**Comment by dev-101** [comment]
Yes, take a look @ your version:

https://github.com/osclass/Osclass/pull/2046/files#diff-cdf04d5f31a7d310baecc8b0e9e5bebaR224

because next line will execute the same thing

**Comment by groomain** [comment]
Thanks for the report.

I've removed this line.

**Pull request merged**
