### PR TITLE
noCaptcha ReCaptcha - 

### PR DESCRIPTION
**Pull request by conejoninja**
Google has introduced a new recaptcha : http://googleonlinesecurity.blogspot.com.es/2014/12/are-you-robot-introducing-no-captcha.html

YOU NEED TO GENERATE NEW RECAPTCHA KEYS AT https://www.google.com/recaptcha/admin

WARNING: Recaptcha will stop working until you generate new keys compatible with API v2

### CODE REVIEW

**Comment by dev-101** [comment]
Hi Conejo, why did you put this label? So far it is working without any issues* - is your experience different?

* except the fact that second layer verification comes too often, seems that Google will have to tweak it som more.

**Comment by conejoninja** [comment]
Ah, the reason is that you need to reissue the recaptcha keys, it will not work with old recaptcha keys, you need to go to the website and generate a new one. This could potentially broke a lot of websites, so I need to add some code to switch between old/new recaptcha.

**Comment by dev-101** [comment]
Ah, OK, thanks!

**Comment by dev-101** [comment]
Hi Conejo,
It seems that themes like Bender will need to be updated, because of a duplicate submit buttons. I already noticed this earlier in discussion, but now realized thanks to a member who tested it.

http://forums.osclass.org/development/how-can-i-add-the-new-no-recaptcha-to-my-site/

Simply removing L1210-L1211 in utils.php is not good for Bender since it breaks submit function, even if replaced with &lt;input&gt;, and adding value="submit", but removal of L1210-L1211 solves duplicate submit form for other themes like Modern.

**Comment by dev-101** [comment]
Maybe the best way is to drop captcha from the core entirely and transform it into plugin. One member already made initial work with noCaptcha in a different way (but it still needs fixes):

http://forums.osclass.org/plugins-20/(free-plugin)-nocaptcha-recaptcha/

This would be much better in terms of future changes to Captcha and core maintenance.

**Comment by conejoninja** [comment]
issue #1823

**Pull request closed without merging**
